### USER REGISTER
POST http://localhost:8080/auth-api/register
Content-Type: application/json

{
    "name": "user2",
    "email": "user2@example.com",
    "password": "user2"
}

### USER LOGIN
POST http://localhost:8080/auth-api/login
Content-Type: application/json

{
    "email": "user2@example.com",
    "password": "user2"
}


### USER PROFILE
GET http://localhost:8080/auth-api/profile


### USER UPDATE 
PUT http://localhost:8080/auth-api/profile
Content-Type: application/json
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZjlhMDEzYTAyZGQ3NjcyYzk0M2YzYyIsImVtYWlsIjoidXNlcjJAZXhhbXBsZS5jb20iLCJpYXQiOjE3Nzc5NjcyMjgsImV4cCI6MTc3ODA1MzYyOH0.oGKV9w-GCQ10xOEqsaOj5_TzK2D35QMphUAozRi5HMo; Path=/; HttpOnly; SameSite=Lax

{
    "name": "user2-updated",
    "email": "user2@example.com",
    "password": "user2",
    "userProfile":""
}


### USER DELETE
DELETE http://localhost:8080/auth-api/profile


### USER LOGOUT
GET http://localhost:8080/auth-api/logout
