### Adding a new collaborator to a repository
POST http://localhost:4000/collab-api/collaborator
Content-Type: application/json

{
    "repoId": "69facdf511ee35540068cb45",
    "userId": "69face3911ee35540068cb46",
    "role": "collaborator"
}


### Listing all collaborators of a repository
GET http://localhost:4000/collab-api/collaborators/69facdf511ee35540068cb45


###updating a collaborator's role in a repository
PUT http://localhost:4000/collab-api/collaborator/69facdf511ee35540068cb45/69face3911ee35540068cb46
Content-Type: application/json

{
    "role": "viewer"
}


### Removing a collaborator from a repository
DELETE http://localhost:4000/collab-api/collaborator/69facdf511ee35540068cb45/69face3911ee35540068cb46