### creating new repository
POST http://localhost:8080/repo-api/repo
Content-Type: application/json

{
    "name": "repo1",
    "description": "this is repo1"
}

### getting all repositories
GET http://localhost:8080/repo-api/repo

### getting repository by id
GET http://localhost:8080/repo-api/repo/69f9a5bf53eb87b6bc6b49a3

### Updating repository by id
PUT http://localhost:8080/repo-api/repo/69f9a5bf53eb87b6bc6b49a3
Content-Type: application/json

{
    "name": "repo1-updated",
    "description": "this is repo1-updated"
}